apiVersion: v1
kind: Namespace
metadata:
  name: mfnano
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mfnano-sa
  namespace: mfnano
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mfnano-sa-role
  namespace: mfnano
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mfnano-sa-binding
  namespace: mfnano
subjects:
- kind: ServiceAccount
  name: mfnano-sa
  namespace: mfnano
roleRef:
  kind: ClusterRole
  name: mfnano-sa-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mfnano
  namespace: mfnano
spec:
  selector:
    matchLabels:
      app: mfnano
  template:
    metadata:
      labels:
        app: mfnano
    spec:
      hostNetwork: true
      serviceAccountName: mfnano-sa
      hostname: mfnano
      containers:
      - name: mfnano
        image: registry.jxit.net.cn:5000/uniserver/uniprobe:k8s-1664
        imagePullPolicy: Always
        command:    
        - sh                
        - -xc                              
        - |
          HTTP_SERVER="demo.microflow.io:9000"
          TOKEN="13plt363ce0b3bbmrggdbhbi67iafffn52ehvoa6uksoi1j1o2bi"
          /opt/up-install/uniprobe -n $HTTP_SERVER -a $TOKEN > /dev/null 2>&1
